sudo: false

addons:
 apt:
   sources:
   - ubuntu-toolchain-r-test

matrix:
    include:
      - os: linux

before_install:
  - node --version
  - npm --version

install:
  - npm set progress=false
  - npm install -g grunt-cli
  - npm install

script:    
  - grunt --version
  - grunt
